/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;
import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class Pinjaman extends javax.swing.JFrame implements HitungAngsuran {

    /**
     * Creates new form Pinjaman
     */
    public Pinjaman() {
        initComponents();
    }
    
    public class MainJumlah extends Bunga{
        private int ajuan;
        
        @Override
        public void setAjuan(int awal){
            ajuan = awal;
        }
        
        @Override
        public int getAjuan(){
            return ajuan;
        }
    }
    
    @Override
    public double masaAngsuran(){
        MainJumlah angsur = new MainJumlah();

        angsur.setAjuan(Integer.parseInt(inputAjuan.getText()));
        angsur.setJangka(Integer.parseInt(inputJangka.getText()));
        if (angsuranHarian.isSelected()){
            angsur.setMasa(30);
        }else if (angsuranMingguan.isSelected()){
            angsur.setMasa(4);
        }else if (angsuranBulanan.isSelected()){
            angsur.setMasa(1);
        }
        angsur.setPokok(angsur.getAjuan()/angsur.getJangka()/angsur.getMasa());
        angsur.setBunga(angsur.getAjuan() * 0.5/100 /angsur.getMasa());
        
        double a;
        a = angsur.getPokok() + angsur.getbunga();
        
        return a;
    }
    
    @Override
    public double jumlahAngsuran(){
        MainJumlah angsur = new MainJumlah();

        angsur.setAjuan(Integer.parseInt(inputAjuan.getText()));
        angsur.setJangka(Integer.parseInt(inputJangka.getText()));
        if (angsuranHarian.isSelected()){
            angsur.setMasa(30);
        }else if (angsuranMingguan.isSelected()){
            angsur.setMasa(4);
        }else if (angsuranBulanan.isSelected()){
            angsur.setMasa(1);
        }
        angsur.setPokok(angsur.getAjuan() / angsur.getJangka() / angsur.getMasa());
        angsur.setBunga(angsur.getAjuan() * 0.5/100 /angsur.getMasa());
        angsur.setAngs(angsur.getPokok() + angsur.getbunga());
        
        double b;
        b = angsur.getAngs()*angsur.getMasa()*angsur.getJangka();
        
        return b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        polaAngsuran = new javax.swing.ButtonGroup();
        titleGUI = new javax.swing.JLabel();
        javax.swing.JLabel labelAjuan = new javax.swing.JLabel();
        inputAjuan = new javax.swing.JTextField();
        javax.swing.JLabel labelJangka = new javax.swing.JLabel();
        inputJangka = new javax.swing.JTextField();
        javax.swing.JLabel labelBulan = new javax.swing.JLabel();
        labelPilihKredit = new javax.swing.JLabel();
        pilihKredit = new javax.swing.JComboBox<>();
        javax.swing.JLabel labelPola = new javax.swing.JLabel();
        angsuranHarian = new javax.swing.JRadioButton();
        angsuranMingguan = new javax.swing.JRadioButton();
        angsuranBulanan = new javax.swing.JRadioButton();
        total = new javax.swing.JButton();
        labelMasaAngsuran = new javax.swing.JLabel();
        masaAngsuran = new javax.swing.JTextField();
        totalAngsuran = new javax.swing.JTextField();
        labelTotalAngsuran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peminjanman Bank GUI");
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 370));

        titleGUI.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        titleGUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleGUI.setText("PEMINJAMAN KUR BANK BRI");
        titleGUI.setToolTipText("");

        labelAjuan.setText("Jumlah Ajuan : ");

        inputAjuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAjuanActionPerformed(evt);
            }
        });

        labelJangka.setText("Jangka Waktu : ");

        inputJangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJangkaActionPerformed(evt);
            }
        });

        labelBulan.setText("Bulan");

        labelPilihKredit.setText("Pilih Jenis Kredit : ");

        pilihKredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KUR Mikro", "KUR Kecil", "KUR TKI" }));
        pilihKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKreditActionPerformed(evt);
            }
        });

        labelPola.setText("Pola Angsuran : ");

        polaAngsuran.add(angsuranHarian);
        angsuranHarian.setText("Harian");
        angsuranHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angsuranHarianActionPerformed(evt);
            }
        });

        polaAngsuran.add(angsuranMingguan);
        angsuranMingguan.setText("Mingguan");
        angsuranMingguan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angsuranMingguanActionPerformed(evt);
            }
        });

        polaAngsuran.add(angsuranBulanan);
        angsuranBulanan.setText("Bulanan");
        angsuranBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angsuranBulananActionPerformed(evt);
            }
        });

        total.setText("Hitung Bunga");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        labelMasaAngsuran.setText("Angsuran per masa : ");

        masaAngsuran.setEditable(false);
        masaAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaAngsuranActionPerformed(evt);
            }
        });

        totalAngsuran.setEditable(false);
        totalAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAngsuranActionPerformed(evt);
            }
        });

        labelTotalAngsuran.setText("Total Angsuran : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPola)
                        .addGap(25, 25, 25)
                        .addComponent(angsuranBulanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(angsuranMingguan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angsuranHarian))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMasaAngsuran)
                        .addGap(4, 4, 4)
                        .addComponent(masaAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAjuan)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelJangka)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputAjuan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputJangka, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBulan))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotalAngsuran)
                        .addGap(24, 24, 24)
                        .addComponent(totalAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPilihKredit)
                        .addGap(18, 18, 18)
                        .addComponent(pilihKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPilihKredit)
                    .addComponent(pilihKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAjuan)
                    .addComponent(inputAjuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJangka)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBulan)
                        .addComponent(inputJangka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPola)
                            .addComponent(angsuranBulanan)
                            .addComponent(angsuranMingguan)
                            .addComponent(angsuranHarian)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(total)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masaAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelMasaAngsuran)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelTotalAngsuran)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        masaAngsuran.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihKreditActionPerformed

    private void inputAjuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAjuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAjuanActionPerformed

    private void inputJangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJangkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJangkaActionPerformed

    private void angsuranBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angsuranBulananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angsuranBulananActionPerformed

    private void angsuranMingguanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angsuranMingguanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angsuranMingguanActionPerformed

    private void angsuranHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angsuranHarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angsuranHarianActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        int inkre = pilihKredit.getSelectedIndex();
        int ajuan = Integer.parseInt(inputAjuan.getText());
        
        switch (inkre){
            case 0: {
                try{
                    if(ajuan>25000000){
                        throw new ArrayIndexOutOfBoundsException();
                    }else{
                        masaAngsuran.setText(String.format("%.1f",masaAngsuran()));
                        totalAngsuran.setText(String.format("%.1f",jumlahAngsuran()));
                        break;
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Batas Maksimal KUR Mikro adalah Rp. 25.000.000");
                    break;
                }
            }
            case 1: {
                try{
                    if(ajuan<25000000 || ajuan>100000000){
                        throw new ArrayIndexOutOfBoundsException();
                    }else{
                        masaAngsuran.setText(String.format("%.1f",masaAngsuran()));
                        totalAngsuran.setText(String.format("%.1f",jumlahAngsuran()));
                        break;
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Batas peminjaman KUR Ritel adalah Rp. 25.000.000 - Rp. 100.000.000");
                    break;
                }
            }
            case 2: {
                try{
                    if(ajuan>25000000){
                        throw new ArrayIndexOutOfBoundsException();
                    }else{
                        masaAngsuran.setText(String.format("%.1f",masaAngsuran()));
                        totalAngsuran.setText(String.format("%.1f",jumlahAngsuran()));
                        break;
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"KUR TKI tidak boleh lebih dari Rp. 25.000.000");
                    break;
                }
            }
        }
        
    }//GEN-LAST:event_totalActionPerformed

    private void masaAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masaAngsuranActionPerformed

    private void totalAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAngsuranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton angsuranBulanan;
    private javax.swing.JRadioButton angsuranHarian;
    private javax.swing.JRadioButton angsuranMingguan;
    private javax.swing.JTextField inputAjuan;
    private javax.swing.JTextField inputJangka;
    private javax.swing.JLabel labelMasaAngsuran;
    private javax.swing.JLabel labelPilihKredit;
    private javax.swing.JLabel labelTotalAngsuran;
    private javax.swing.JTextField masaAngsuran;
    private javax.swing.JComboBox<String> pilihKredit;
    private javax.swing.ButtonGroup polaAngsuran;
    private javax.swing.JLabel titleGUI;
    private javax.swing.JButton total;
    private javax.swing.JTextField totalAngsuran;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane(String field_input_harus_terisi_semua) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
